# Generated by Django 5.2.7 on 2025-10-23 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_profile_pen_name_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
